import { useState } from 'react';
import { Alert, Badge, Button, Card, Form, Spinner } from 'react-bootstrap';
import { api } from '../api';
import { useApp } from '../store';

// Lesson Q&A (answers only from this course's lessons) and AI-generated practice quiz. Enrolled users only.
export function AskLessons({ slug }) {
    const { t } = useApp();
    const [state, setState] = useState({});
    const ask = async e => {
        e.preventDefault();
        const question = e.currentTarget.question.value.trim();
        if (!question) return;
        setState({ busy: true });
        try { setState({ answer: await api(`courses/${slug}/ask/`, { question }) }); }
        catch (err) { setState({ error: err.message }); }
    };
    return (
        <Card className="card-soft mb-4">
            <Card.Body>
                <h5 className="fw-bold"><i className="bi bi-question-circle me-2" />{t('Ask about the lessons')}</h5>
                <Form onSubmit={ask} className="d-flex gap-2">
                    <Form.Control name="question" placeholder={t('e.g. What causes inflation?')} maxLength={500} required />
                    <Button type="submit" variant="accent" disabled={state.busy}>{state.busy ? <Spinner size="sm" /> : t('Ask')}</Button>
                </Form>
                {state.error && <Alert variant="warning" className="mt-3 mb-0">{state.error}</Alert>}
                {state.answer && <div className="mt-3 bg-body rounded-3 p-3">
                    <p className="mb-2" style={{ whiteSpace: 'pre-line' }}>{state.answer.answer}</p>
                    {state.answer.sources.map(s => <Badge key={s} bg="info" className="me-1">{s}</Badge>)}
                </div>}
            </Card.Body>
        </Card>
    );
}

export function Quiz({ slug }) {
    const { t } = useApp();
    const [state, setState] = useState({});
    const [picked, setPicked] = useState({});
    const [done, setDone] = useState(false);
    const load = async () => {
        setState({ busy: true }); setPicked({}); setDone(false);
        try { setState({ questions: (await api(`courses/${slug}/quiz/`, {})).questions }); }
        catch (err) { setState({ error: err.message }); }
    };
    const qs = state.questions || [];
    const score = qs.filter((q, i) => picked[i] === q.answer_index).length;
    return (
        <Card className="card-soft mb-4">
            <Card.Body>
                <div className="d-flex justify-content-between align-items-center mb-3">
                    <h5 className="fw-bold m-0"><i className="bi bi-patch-question me-2" />{t('Practice quiz')}</h5>
                    <Button variant="accent" onClick={load} disabled={state.busy}>{state.busy ? <Spinner size="sm" /> : t(qs.length ? 'New quiz' : 'Generate quiz')}</Button>
                </div>
                {state.error && <Alert variant="warning" className="mb-0">{state.error}</Alert>}
                {qs.map((q, i) => (
                    <div key={i} className="bg-body rounded-3 p-3 mb-3">
                        <p className="fw-bold mb-2">{i + 1}. {q.question}</p>
                        {q.options.map((o, j) => (
                            <Form.Check key={j} type="radio" id={`q${i}-${j}`} name={`q${i}`} label={o}
                                checked={picked[i] === j} onChange={() => !done && setPicked(p => ({ ...p, [i]: j }))}
                                className={done && j === q.answer_index ? 'text-success fw-bold' : done && picked[i] === j ? 'text-danger' : ''} />
                        ))}
                        {done && <small className="text-body-secondary">{q.explanation}</small>}
                    </div>
                ))}
                {!!qs.length && (done
                    ? <Alert variant={score === qs.length ? 'success' : 'info'} className="mb-0">{t('Score')}: {score}/{qs.length}</Alert>
                    : <Button variant="primary" onClick={() => setDone(true)} disabled={Object.keys(picked).length < qs.length}>{t('Check answers')}</Button>)}
                <small className="text-body-secondary d-block mt-2">{t('Questions are generated by AI from the lessons and may contain mistakes.')}</small>
            </Card.Body>
        </Card>
    );
}
