# Generated by Django 5.2.17 on 2026-10-06 04:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='summary',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='article',
            name='summary_draft',
            field=models.TextField(blank=True, help_text='AI draft. Review it, then use the "Apply drafts" action.'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='ai_label',
            field=models.CharField(blank=True, choices=[('', 'Not checked'), ('clean', 'Clean'), ('spam', 'Spam'), ('toxic', 'Toxic')], max_length=10),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='ai_reason',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddIndex(
            model_name='testimonial',
            index=models.Index(fields=['is_approved', '-created_at'], name='content_tes_is_appr_eba48b_idx'),
        ),
    ]
