// Vietnamese UI strings, keyed by the English text. Missing keys fall back to English.
// Course/article content comes from the database and is not translated here.
export const VI = {
    // layout
    'Home': 'Trang chủ', 'Courses': 'Khóa học', 'Podcasts': 'Podcast', 'Articles': 'Bài viết', 'About Us': 'Giới thiệu',
    'Menu': 'Menu', 'Cart': 'Giỏ hàng', 'Account': 'Tài khoản', 'Login': 'Đăng nhập', 'Go to course': 'Vào học',
    'Dark mode': 'Chế độ tối', 'Light mode': 'Chế độ sáng',
    'Share your experience': 'Chia sẻ trải nghiệm',
    'Something went wrong on this page.': 'Trang này gặp lỗi.', 'Reload': 'Tải lại',
    // search
    'Search courses, podcasts, articles...': 'Tìm khóa học, podcast, bài viết...', 'Search': 'Tìm kiếm',
    'Course': 'Khóa học', 'Podcast': 'Podcast', 'Article': 'Bài viết', 'Search results': 'Kết quả tìm kiếm',
    'Type at least 2 characters.': 'Nhập ít nhất 2 ký tự.', 'No results found.': 'Không tìm thấy kết quả.',
    // home
    'Welcome to the Economic Communication Center': 'Chào mừng đến với Economic Communication Center',
    'Your gateway to understanding economics through engaging content.': 'Cánh cửa giúp bạn hiểu kinh tế qua nội dung hấp dẫn.',
    "Let's Get Started": 'Bắt đầu ngay', 'Popular courses': 'Khóa học nổi bật', 'View course': 'Xem khóa học',
    'What our students say': 'Học viên nói gì về chúng tôi', 'No comments yet.': 'Chưa có bình luận.',
    'All courses': 'Tất cả khóa học',
    // pages
    'Learn economics step by step with practical online courses.': 'Học kinh tế từng bước với các khóa học trực tuyến thực tế.',
    'Listen and learn on the go.': 'Vừa nghe vừa học mọi lúc mọi nơi.', 'Short reads about economics and markets.': 'Bài đọc ngắn về kinh tế và thị trường.',
    'Nothing here yet.': 'Chưa có nội dung.', 'Host': 'Người dẫn', 'listeners': 'lượt nghe', 'readers': 'lượt đọc', 'Read more': 'Đọc tiếp',
    'hours': 'giờ', 'students': 'học viên', 'days left': 'ngày còn lại', 'Add to cart': 'Thêm vào giỏ', 'In cart': 'Đã trong giỏ',
    'Enrolled': 'Đã ghi danh', 'Lessons': 'Bài học', 'Lessons are coming soon.': 'Bài học sắp ra mắt.',
    'Buy this course to unlock the lesson': 'Mua khóa học để mở bài học', 'log in': 'đăng nhập', 'first': 'trước',
    'Enrolled students get an AI assistant that answers questions from these lessons and builds practice quizzes.':
        'Học viên đã ghi danh có trợ lý AI trả lời câu hỏi từ bài học và tạo quiz luyện tập.',
    'Ask about the lessons': 'Hỏi về bài học', 'e.g. What causes inflation?': 'VD: Nguyên nhân gây lạm phát là gì?', 'Ask': 'Hỏi',
    'Practice quiz': 'Quiz luyện tập', 'New quiz': 'Quiz mới', 'Generate quiz': 'Tạo quiz', 'Check answers': 'Chấm điểm', 'Score': 'Điểm',
    'Questions are generated by AI from the lessons and may contain mistakes.': 'Câu hỏi do AI tạo từ bài học và có thể sai.',
    'Page not found': 'Không tìm thấy trang', 'The page you are looking for does not exist.': 'Trang bạn tìm không tồn tại.',
    'Back to home': 'Về trang chủ',
    // cart
    'Your Cart': 'Giỏ hàng của bạn', 'Review your courses and check out.': 'Xem lại khóa học và thanh toán.',
    'Your cart is empty.': 'Giỏ hàng trống.', 'Browse courses': 'Xem khóa học', 'Remove': 'Xóa', 'Total': 'Tổng',
    'Checkout': 'Thanh toán', 'Log in to checkout': 'Đăng nhập để thanh toán', 'Order': 'Đơn hàng', 'is': 'đã', 'Go to my courses': 'Đến khóa học của tôi',
    // account
    'Log in to buy courses and track your learning.': 'Đăng nhập để mua khóa học và theo dõi việc học.',
    'Your courses, orders and feedback.': 'Khóa học, đơn hàng và góp ý của bạn.', 'Username or email': 'Tên đăng nhập hoặc email',
    'Password': 'Mật khẩu', 'Create an account': 'Tạo tài khoản', 'Username': 'Tên đăng nhập', 'Email': 'Email',
    'First name': 'Tên', 'Last name': 'Họ', 'Password (8+ characters)': 'Mật khẩu (từ 8 ký tự)', 'Register': 'Đăng ký',
    'Hello': 'Xin chào', 'Logout': 'Đăng xuất', 'My Courses': 'Khóa học của tôi', 'No courses yet.': 'Chưa có khóa học.',
    'My Orders': 'Đơn hàng của tôi', 'No orders yet.': 'Chưa có đơn hàng.', 'What do you think about our courses?': 'Bạn nghĩ gì về khóa học của chúng tôi?',
    'Send': 'Gửi', 'to share your experience.': 'để chia sẻ trải nghiệm.', 'Thanks! Your comment will appear after an admin approves it.': 'Cảm ơn! Bình luận sẽ hiển thị sau khi admin duyệt.',
    'paid': 'đã thanh toán', 'pending': 'chờ thanh toán', 'cancelled': 'đã hủy', 'student': 'học viên', 'teacher': 'giáo viên', 'admin': 'quản trị',
    // about
    'Economics made clear, one lesson at a time.': 'Kinh tế dễ hiểu, từng bài một.', 'Our Mission': 'Sứ mệnh',
    'Economic Communication Center helps students and working people understand economics and talk about it with confidence. We turn complex ideas into short, practical courses, podcasts and articles in plain English.':
        'Economic Communication Center giúp sinh viên và người đi làm hiểu kinh tế và tự tin trao đổi về nó. Chúng tôi biến ý tưởng phức tạp thành khóa học, podcast và bài viết ngắn gọn, thực tế, dễ hiểu.',
    'What We Offer': 'Chúng tôi mang đến', 'Online courses': 'Khóa học trực tuyến', 'Podcast episodes': 'Tập podcast', 'Blog articles': 'Bài viết blog',
    'Our Teachers': 'Đội ngũ giáo viên', 'course': 'khóa học', 'Contact Us': 'Liên hệ', 'Your name': 'Họ tên', 'Your email': 'Email của bạn',
    'Your message': 'Nội dung', 'Send message': 'Gửi tin nhắn', 'Thanks! We will reply to your email soon.': 'Cảm ơn! Chúng tôi sẽ sớm phản hồi qua email.',
    // chat
    'Course advisor': 'Tư vấn khóa học', 'Close': 'Đóng', 'Ask about our courses...': 'Hỏi về khóa học...',
    'Hi! I am the course advisor. Tell me what you want to learn and I will suggest courses.':
        'Xin chào! Mình là trợ lý tư vấn. Hãy cho mình biết bạn muốn học gì, mình sẽ gợi ý khóa học phù hợp.',
    'AI answers can be wrong. Prices are checked at checkout.': 'AI có thể trả lời sai. Giá được kiểm tra lại khi thanh toán.',
};
